### PR TITLE
Fix issue introduced by React portal support for InfoBox

### PR DESCRIPTION
**Pull request by GuillaumeSalles**
Don't wait for componentDidMount to create portal root.

### CODE REVIEW

**Comment by evanhaldane** [comment]
why is `componentDidMount` not firing?

**Comment by GuillaumeSalles** [comment]
@evanhaldane 
> why is componentDidMount not firing?

Sorry, I didn't really explain what was happening.

Before this fix, the lifecycle was:

- `componentWillMount` create the google InfoBox
- `render` returns null because `InfoBox.getContent()` was empty (L 179)
- `componentDidMount` call `InfoBox.setContent()` with an empty div

Nothing is rendered at this point. If you mouse over the map, react is going through the `render` method again and `InfoBox.getContent()` now return a div and the portal is created properly.

With the fix:
- `componentWillMount` create the google InfoBox
- `render`: if InfoBox.getContent() is empty, call InfoBox.setContent() with an empty div and render the portal

It's currently working on bcom master, because with Analytics is triggering another render right after the componentDidMount (but it shouldn't)

**Comment by evanhaldane** [comment]
Ah so _if_ I understand correctly, `setContent` could also go in the constructor and remove the need to check the status in the `render`.

**Review by evanhaldane — APPROVED** [review]

**Comment by GuillaumeSalles** [comment]
Not the constructor, but calling setContent in componentWillMount could work

**Review by alessbell — COMMENTED** [review]
Looks like I'm stuck in limbo as a requested reviewer (cannot remove myself)... seeing if this absolves me

**Pull request merged**
